#!/usr/bin/env python3
"""Aggregate phase results into HEADLINE.md and COSTS.md.

Reads phases/<phase>/results/<model>/run_*/{attempts.jsonl,evaluation.jsonl}
and writes:
  phases/<phase>/HEADLINE.md   - per-model success table
  phases/<phase>/COSTS.md      - the output of estimate.py --md (passed in)

REPORT.md is intentionally NOT rewritten so curated prose survives.
"""

from __future__ import annotations

import argparse
import csv
import json
import statistics
import sys
from collections import defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]


def load_attempts(phase_dir: Path):
    """Yield (model, run_index, record) for every attempts.jsonl row."""
    for model_dir in sorted((phase_dir / "results").glob("*")):
        if not model_dir.is_dir():
            continue
        model = model_dir.name.replace("__", "/")
        for run_dir in sorted(model_dir.glob("run_*")):
            try:
                run_idx = int(run_dir.name.split("_", 1)[1])
            except (IndexError, ValueError):
                continue
            f = run_dir / "attempts.jsonl"
            if not f.exists():
                continue
            for line in f.read_text().splitlines():
                line = line.strip()
                if not line:
                    continue
                try:
                    yield model, run_idx, json.loads(line)
                except json.JSONDecodeError:
                    continue


def load_evals(phase_dir: Path):
    """Yield (model, run_index, record) for every evaluation.jsonl row."""
    for model_dir in sorted((phase_dir / "results").glob("*")):
        if not model_dir.is_dir():
            continue
        model = model_dir.name.replace("__", "/")
        for run_dir in sorted(model_dir.glob("run_*")):
            try:
                run_idx = int(run_dir.name.split("_", 1)[1])
            except (IndexError, ValueError):
                continue
            f = run_dir / "evaluation.jsonl"
            if not f.exists():
                continue
            for line in f.read_text().splitlines():
                line = line.strip()
                if not line:
                    continue
                try:
                    yield model, run_idx, json.loads(line)
                except json.JSONDecodeError:
                    continue


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--phase", required=True)
    ap.add_argument("--target-set", required=True)
    ap.add_argument("--cost-md", type=Path, required=True,
                    help="Path to a markdown file produced by tools/cost/estimate.py --md")
    args = ap.parse_args()

    phase_dir = REPO_ROOT / "phases" / args.phase
    if not phase_dir.is_dir():
        print(f"error: phase dir not found: {phase_dir}", file=sys.stderr)
        return 2

    targets_csv = REPO_ROOT / "targets" / args.target_set / "targets.csv"
    n_targets = sum(1 for _ in csv.DictReader(targets_csv.open())) if targets_csv.exists() else 0

    # Aggregate attempts: per model, count distinct (target_id, run_index) pairs that
    # produced a candidate (proxy for "agent emitted code").
    attempts_per_model = defaultdict(set)
    turns_per_model = defaultdict(list)
    for model, run_idx, rec in load_attempts(phase_dir):
        tid = rec.get("target_id")
        if tid:
            attempts_per_model[model].add((tid, run_idx))
        if "turns" in rec and isinstance(rec["turns"], int):
            turns_per_model[model].append(rec["turns"])

    # Aggregate evals: per model, compile_ok / run_ok counts over (target_id, run_index).
    evals_per_model = defaultdict(lambda: {"total": 0, "compile_ok": 0, "run_ok": 0})
    for model, _run_idx, rec in load_evals(phase_dir):
        s = evals_per_model[model]
        s["total"] += 1
        if rec.get("compile_ok"):
            s["compile_ok"] += 1
        if rec.get("run_ok"):
            s["run_ok"] += 1

    # ---- HEADLINE.md ----
    lines = []
    lines.append(f"# Phase `{args.phase}` — headline summary")
    lines.append("")
    lines.append(f"Target set: **{args.target_set}** ({n_targets} cells)")
    lines.append("")
    lines.append("Auto-generated by `.github/scripts/build_report.py`. Do not hand-edit; rerun the aggregator instead.")
    lines.append("")
    lines.append("## Per-model results")
    lines.append("")
    lines.append("| Model | Cells attempted | Eval rows | Compile OK | Run OK | Compile% | Run% | Median turns |")
    lines.append("|---|---:|---:|---:|---:|---:|---:|---:|")
    all_models = sorted(set(attempts_per_model) | set(evals_per_model))
    for m in all_models:
        a = len(attempts_per_model.get(m, set()))
        e = evals_per_model.get(m, {"total": 0, "compile_ok": 0, "run_ok": 0})
        comp_pct = (100.0 * e["compile_ok"] / e["total"]) if e["total"] else 0.0
        run_pct = (100.0 * e["run_ok"] / e["total"]) if e["total"] else 0.0
        turns = turns_per_model.get(m, [])
        med_turns = statistics.median(turns) if turns else "—"
        lines.append(
            f"| `{m}` | {a} | {e['total']} | {e['compile_ok']} | {e['run_ok']} | {comp_pct:.1f}% | {run_pct:.1f}% | {med_turns} |"
        )
    lines.append("")
    lines.append("Definitions:")
    lines.append("- *Cells attempted*: distinct `(target_id, run_index)` pairs the model emitted code for.")
    lines.append("- *Eval rows*: rows in `evaluation.jsonl` (one per generated `test.cs` after evaluator scan).")
    lines.append("- *Compile OK*: evaluator built the test against the cloned repo successfully.")
    lines.append("- *Run OK*: `dotnet test` exited 0 on the produced test.")
    lines.append("")

    headline_path = phase_dir / "HEADLINE.md"
    headline_path.write_text("\n".join(lines) + "\n")
    print(f"wrote {headline_path}")

    # ---- COSTS.md ----
    cost_md_path = phase_dir / "COSTS.md"
    cost_text = args.cost_md.read_text()
    cost_md_path.write_text(
        f"# Phase `{args.phase}` — cost report\n\n"
        f"Auto-generated from `tools/cost/estimate.py`. Do not hand-edit.\n\n"
        f"{cost_text}"
    )
    print(f"wrote {cost_md_path}")

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
